name = "TemplateDocsVitePress"
uuid = "6096575d-799d-4116-8a3c-c22801a427cb"
authors = ["Lazaro Alonso <lazarus.alon@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
